services:
  mysql:
    image: mysql:8.4
    container_name: vibr-mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "vibr"
      TZ: "Asia/Seoul"
    command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p1234" ]
      interval: 5s
      timeout: 3s
      retries: 20
  neo4j:
    image: neo4j:5.15
    container_name: vibr-neo4j
    ports:
      - "7474:7474" # HTTP (브라우저 콘솔용)
      - "7687:7687" # Bolt (애플리케이션 연결용)
    environment:
      NEO4J_AUTH: neo4j/1234
    volumes:
      - ./neo4j/data:/data
      retries: 10