@baseUrl = http://localhost:3002/api
@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTExMTExMS0xMTExLTExMTEtMTExMS0xMTExMTExMTExMTEiLCJpYXQiOjE3NjgzNzYwMjYsImV4cCI6MTc3MzU2MDAyNn0.qnflWdgcGE2bCHVau498Ox87tSD8LUiU4mo6Oy7_DE4

############################################################
# 알림 API 테스트
############################################################

### 알림 확인 - GET /noti
GET {{baseUrl}}/noti HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}

### 알림 읽기 - PATCH /noti/:id
PATCH {{baseUrl}}/noti/22222222-2222-2222-2222-222222222222 HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{}

### 알림 읽기 실패(잘못된 UUID) - PATCH /noti/:id
PATCH {{baseUrl}}/noti/4444444-4444--4444-4444-444444444444 HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{}

### 알림 삭제 - DELETE /noti/:id
DELETE {{baseUrl}}/noti/22222222-2222-2222-2222-222222222222 HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}

### 알림 삭제 실패(잘못된 UUID) - DELETE /noti/:id
DELETE {{baseUrl}}/noti/4444444-4444--4444-4444-444444444444 HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}
