@baseUrl = http://localhost:3002/api
@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTExMTExMS0xMTExLTExMTEtMTExMS0xMTExMTExMTExMTEiLCJpYXQiOjE3NjgzNzYwMjYsImV4cCI6MTc3MzU2MDAyNn0.qnflWdgcGE2bCHVau498Ox87tSD8LUiU4mo6Oy7_DE4

############################################################
# 플레이리스트 API 테스트
############################################################

### 전체 플리 조회 - GET /playlist
GET {{baseUrl}}/playlist HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}

### 새로운 플리 추가 - POST /playlist
POST {{baseUrl}}/playlist HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "title": "새로운 플레이리스트!!"
}

### 새로운 플리 추가 2 - title 없이 디폴트로 생성
POST {{baseUrl}}/playlist HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

### 플리 상세 조회
GET {{baseUrl}}/playlist/pppppppp-pppp-pppp-pppp-pppppppppppp HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}

### 플리 제목 수정
PATCH {{baseUrl}}/playlist/pppppppp-pppp-pppp-pppp-pppppppppppp HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "title": "수정된 플리 제목~!!"
}

### 플리 삭제
DELETE {{baseUrl}}/playlist/pppppppp-pppp-pppp-pppp-pppppppppppp HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}

### 플리에 음악 추가
POST {{baseUrl}}/playlist/pppppppp-pppp-pppp-pppp-pppppppppppp/music HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  musics: [
    {
      id: "cccccccc-cccc-cccc-cccc-cccccccccccc",
      trackUri: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/86/4d/a5/864da591-eeb0-27db-bbfa-a190ee20a05c/mzaf_17780542814473670833.plus.aac.p.m4a",
      albumCoverUrl: "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/12/31/63/12316366-55bb-065c-8ad9-47e107fa79b2/AKMU_NEXT_EPISODE.jpg/600x600bb.jpg",
      title: "낙하 (with 아이유)",
      artistName: "악뮤",
      durationMs: 30000,
      provider: "itunes",
    },
    {
      trackUri: "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/5b/88/47/5b8847a9-21eb-2393-8d6a-8f37108da2e3/mzaf_16072264406110905806.plus.aac.p.m4a",
      albumCoverUrl: "https://is1-ssl.mzstatic.com/image/thumb/Music/v4/8c/e9/c7/8ce9c707-4273-4752-f613-548b8fc773e2/KM0002628-_-0312.jpg/600x600bb.jpg",
      title: "까탈레나",
      artistName: "오렌지카라멜",
      durationMs: 30000,
      provider: "itunes",
    }
  ]
}

### 플리 음악 순서 변경
PUT {{baseUrl}}/playlist/pppppppp-pppp-pppp-pppp-pppppppppppp/music HTTP/1.1
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  musicIds: [
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "22222222-2222-2222-2222-222222222222",
    "11111111-1111-1111-1111-111111111111",
  ]
}
