@baseUrl = http://localhost:3002
@cookie = jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTExMTExMS0xMTExLTExMTEtMTExMS0xMTExMTExMTExMTEiLCJpYXQiOjE3NjgzNzYwMjYsImV4cCI6MTc3MzU2MDAyNn0.qnflWdgcGE2bCHVau498Ox87tSD8LUiU4mo6Oy7_DE4

############################################################
# 게시글 API 테스트
############################################################

### 게시글 생성 - POST /post
POST {{baseUrl}}/post HTTP/1.1
Cookie: {{cookie}}
Content-Type: application/json

{
  "content": "new post~~",
  "thumbnailImgUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/2e/88/88/2e8888ad-a0cf-eece-70a7-1ff81377a3ab/24UMGIM00198.rgb.jpg/600x600bb.jpg",
  "musics": [
    {
      "id": "11111111-1111-1111-1111-111111111111",
      "title": "we cant be friends",
      "artistName": "Ariana Grande",
      "albumCoverUrl": "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/2e/88/88/2e8888ad-a0cf-eece-70a7-1ff81377a3ab/24UMGIM00198.rgb.jpg/600x600bb.jpg",
      "trackUri": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/22/fc/88/22fc885b-27c8-4693-7400-9e774eae9d7a/mzaf_5140833304960295464.plus.aac.p.m4a",
      "provider": "apple",
      "durationMs": 30000
    }
  ]
}

### 게시글 상세 조회 - GET /post/:id
GET {{baseUrl}}/post/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa HTTP/1.1
Cookie: {{cookie}}

### 게시글 수정 - PATCH /post/:id
PATCH {{baseUrl}}/post/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa HTTP/1.1
Cookie: {{cookie}}
Content-Type: application/json

{
  "content": "수정된 내용~~!!"
}

### 게시글 삭제 - DELETE /post/:id
DELETE {{baseUrl}}/post/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa HTTP/1.1
Cookie: {{cookie}}
