### 좋아요 점수 추가 (postId=123)
POST http://localhost:3002/api/trending/123/like
Content-Type: application/json


### 댓글 점수 추가 (postId=123)
POST http://localhost:3002/api/trending/123/comment
Content-Type: application/json


### 조회 점수 추가 (postId=999)
POST http://localhost:3002/api/trending/999/view
Content-Type: application/json


### 인기글 랭킹 조회 (top 10)
GET http://localhost:3002/api/trending?limit=10
